version: '3'
services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8501/_stcore/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src:/src
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: infomdss
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U student" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
